package com.dpgil.pathlinker.path_linker.internal.util;

import java.util.ArrayList;

/**
 * Path class that represents the path generated by PathLinker
 *      Each path contains a path index in the corresponding network,
 *      the total path weight
 *      an array list of nodes names that is included in the path
 *      
 * @author Li Huang
 * @version 12.7.2017
 */
public class PathLinkerPath {
    /** the path index */
    private int pathIndex;
    /** the total weight of the path */
    private double  pathWeight;
    /** the list of nodes in string in order in the path */
    private ArrayList<String> nodeList;

    /**
     * Default constructor
     * @param pathIndex     the path index
     * @param pathWeight    the path weight
     * @param nodeList      the node list
     */
    public PathLinkerPath (int pathIndex, double pathWeight, ArrayList<String> nodeList) {
        this.pathIndex = pathIndex;
        this.pathWeight = pathWeight;
        this.nodeList = nodeList;
    }

    /**
     * Getter method for path index
     * @return the pathIndex
     */
    public int getPathIndex() {
        return pathIndex;
    }

    /**
     * Setter method for path index
     * @param pathIndex the pathIndex to set
     */
    public void setPathIndex(int pathIndex) {
        this.pathIndex = pathIndex;
    }

    /**
     * Getter method for path weight
     * @return the pathWeight
     */
    public double getPathWeight() {
        return pathWeight;
    }

    /**
     * Setter method for path weight
     * @param pathWeight the pathWeight to set
     */
    public void setPathWeight(double pathWeight) {
        this.pathWeight = pathWeight;
    }

    /**
     * Getter method for the node list
     * @return the nodeList
     */
    public ArrayList<String> getNodeList() {
        return nodeList;
    }

    /**
     * Setter method for the node list
     * @param nodeList the nodeList to set
     */
    public void setNodeList(ArrayList<String> nodeList) {
        this.nodeList = nodeList;
    }
}
