package com.dpgil.pathlinker.path_linker.internal.util;

import java.util.ArrayList;

/**
 * Path class that represents the path generated by PathLinker
 *      Each path contains a path index in the corresponding network,
 *      the total path weight
 *      an array list of nodes names that is included in the path
 *      
 * @author Li Huang
 * @version 12.7.2017
 */
public class PathLinkerPath {
    /** the path index */
    private int pathIndex;
    /** the total score of the path */
    private double  pathScore;
    /** the list of nodes in string in order in the path */
    private ArrayList<String> path;

    /**
     * Default constructor
     * @param pathIndex     the path index
     * @param pathScore    the path score
     * @param nodeList      the node list
     */
    public PathLinkerPath (int pathIndex, double pathScore, ArrayList<String> nodeList) {
        this.pathIndex = pathIndex;
        this.pathScore = pathScore;
        this.path = nodeList;
    }

    /**
     * Getter method for path index
     * @return the pathIndex
     */
    public int getPathIndex() {
        return pathIndex;
    }

    /**
     * Getter method for path weight
     * @return the pathWeight
     */
    public double getPathWeight() {
        return pathScore;
    }

    /**
     * Getter method for the node list
     * @return the nodeList
     */
    public ArrayList<String> getNodeList() {
        return path;
    }
}
