package com.dpgil.pathlinker.path_linker.internal.rest;

import java.util.List;

import com.dpgil.pathlinker.path_linker.internal.util.Path;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Class handles PathLinker API function response
 * @author li huang
 * @version 1.3.2017
 */
@ApiModel(value="PathLinker App Response", 
description="PathLinker Analysis Results in CI Format")
public class PathLinkerAppResponse {

    /** SUID of the subnetwork */
    private Long subnetworkSUID;
    /** SUID of the subnetwork view */
    private Long subnetworkViewSUID;
    /** The name of the path rank column correspond to the subnetwork */
    private String pathRankColumnName;
    /** List of PathLinkerPath objects */
    private List<Path> paths;

    /**
     * Getter method of the subnetworkSUID
     * @return subnetworkSUID
     */
    @ApiModelProperty(value = "SUID of the subnetwork created")
    public Long getSubnetworkSUID() {
        return subnetworkSUID;
    }

    /**
     * Setter method of the subnetworkSUID
     * @param subnetworkSUID
     */
    public void setSubNetworkSUID(Long subnetworkSUID) {
        this.subnetworkSUID = subnetworkSUID;
    }

    /**
     * Getter method of the subnetworkViewSUID
     * @return subnetworkViewSUID
     */
    @ApiModelProperty(value = "SUID of the subnetwork view created")
    public Long getSubnetworkViewSUID() {
        return subnetworkViewSUID;
    }

    /**
     * Setter method of the subnetworkViewSUID
     * @param subnetworkViewSUID
     */
    public void setSubnetworkViewSUID(Long subnetworkViewSUID) {
        this.subnetworkViewSUID = subnetworkViewSUID;
    }

    /**
     * Getter method of the pathRankColumnName
     * @return the pathRankColumnName
     */
    @ApiModelProperty(value = "The name of the edge column containing the rank of the first path in which a given edge appears",
            example = "path rank 1")
    public String getPathRankColumnName() {
        return pathRankColumnName;
    }

    /**
     * Setter method of the pathRankColumnName
     * @param pathRankColumnName
     */
    public void setPathRankColumnName(String pathRankColumnName) {
        this.pathRankColumnName = pathRankColumnName;
    }

    /**
     * Getter method of the paths
     * @return paths
     */
    @ApiModelProperty(value = "List of paths generated by the algorithm", required = true)
    public List<Path> getPaths() {
        return paths;
    }

    /**
     * Setter method of the paths
     * @param paths
     */
    public void setPaths(List<Path> paths) {
        this.paths = paths;
    }
}
